planificaciones_homepage:
    path:     /
    defaults: { _controller: PlanificacionesBundle:Default:index }

planificaciones_carga:
    path:     /carga-planificacion
    defaults: { _controller: PlanificacionesBundle:Default:cargaPlanificacion }