planificaciones_ajax:
    resource: "@PlanificacionesBundle/Resources/config/routing/ajax.yml"
    prefix: /ajax/planificaciones

academica_planificaciones_homepage:
    path:     /academica
    defaults: { _controller: PlanificacionesBundle:Default:indexAcademica } 
    
academica_planificaciones_revisar:
    path:     /academica/revisar
    defaults: { _controller: PlanificacionesBundle:Default:revisarPlanificacion }     

planificaciones_homepage:
    path:     /
    defaults: { _controller: PlanificacionesBundle:Planificacion:index }

planificaciones_new:
    path:     /nueva
    defaults: { _controller: PlanificacionesBundle:Planificacion:new }

planificaciones_edit:
    path:     /{id}/editar
    defaults: { _controller: PlanificacionesBundle:Planificacion:edit }