services:

    # https://symfony.com/doc/2.8/doctrine/event_listeners_subscribers.html
    planificaciones.docentes.listener:
        class: PlanificacionesBundle\EventListener\DocenteListener
#        arguments: ['@api_infofich_service']
        tags:
            - { name: doctrine.event_listener, event: prePersist }