services:
    planificaciones.form.type.planificacion:
        class: PlanificacionesBundle\Form\PlanificacionType
        arguments: ['@api_infofich_service']
        tags:
            - { name: form.type }
