services:

    # https://symfony.com/doc/2.8/doctrine/event_listeners_subscribers.html
#    planificaciones.docentes.listener:
#        class: PlanificacionesBundle\EventListener\DocenteListener
##        arguments: ['@api_infofich_service']
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
    
#    planificaciones.planificacion.listener:
#        class: PlanificacionesBundle\EventListener\PlanificacionListener
##        arguments: ['@api_infofich_service']
##        arguments: [ '@service_container' ]
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
#            - { name: doctrine.event_listener, event: preUpdate }
            
#    planificaciones.planificacion.listener:
#        class: PlanificacionesBundle\EventListener\PlanificacionListener
#        arguments: ['@api_infofich_service']
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }
#            - { name: doctrine.event_listener, event: preUpdate }
    
    planificaciones.form.bibliografia_planificacion.type:
        class: PlanificacionesBundle\Form\BibliografiaPlanificacionType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
            
    planificaciones.form.buscador.type:
        class: PlanificacionesBundle\Form\BuscadorType
        arguments: ['@api_infofich_service']
        tags:
            - { name: form.type }
            
    planificaciones.planificacion_voter:
        class:  PlanificacionesBundle\Security\PlanificacionVoter
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
        
    planificaciones_service:
        class: PlanificacionesBundle\Service\PlanificacionService        
        arguments: ["@doctrine.orm.entity_manager"]