<?php

namespace DocentesBundle\Repository;

/**
 * DocenteGradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocenteGradoRepository extends \Doctrine\ORM\EntityRepository
{
    use DocentesTrait;
    
}
