<?php

namespace DocentesBundle\Repository;

/**
 * DocenteGradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocenteGradoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQueryBuilder(){

        $qb = $this->createQueryBuilder('dg');
        $qb->join('dg.persona', 'p');

        $qb->orderBy('p.apellidos', 'ASC');

        return $qb;

    }
    
}
