<?php

namespace DocentesBundle\Repository;

/**
 * DocenteAdscriptoPlanificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocenteAdscriptoRepository extends \Doctrine\ORM\EntityRepository
{
    
    //public function buscarPorDocumento()
    
    
}
