<?php

namespace DocentesBundle\Repository;

use DocentesBundle\Entity\LogActualizacionDocentesGrado;
use Doctrine\ORM\Query\QueryException;

/**
 * AudDocenteGradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogActualizacionDocentesGradoRepository extends \Doctrine\ORM\EntityRepository
{

    public function getQueryBuilder(){

        $qb = $this->createQueryBuilder('l');

        $qb->orderBy('l.fechaActualizacion', 'DESC');

        return $qb;
    }

    /**
     * @return LogActualizacionDocentesGrado|null
     */
    public function getLogMasReciente(){
        $qb = $this->getQueryBuilder();
        $qb->orderBy('l.fechaActualizacion', 'DESC');
        $qb->setMaxResults(1);

        $result = $qb->getQuery()->getResult();
        if(isset($result[0])){
            return $result[0];
        }

        return null;
    }

}
