vehiculos:
    resource: "@VehiculosBundle/Resources/config/routing.yml"
    prefix:   /

docentes_grado:
    resource: "@DocentesBundle/Resources/config/routing.yml"
    prefix:   /

planificaciones:
    resource: "@PlanificacionesBundle/Resources/config/routing.yml"
    prefix:   /planificaciones

app:
    resource: "@AppBundle/Resources/config/routing.yml"    
