## app/config/security.yml

security:
    encoders:
        AppBundle\Entity\Usuario: bcrypt
    
    providers:
        entity_provider:
            entity:
                class: AppBundle\Entity\Usuario
                property: nombreUsuario
                
        
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # IMPORTANTE
        #SI SE LE CAMBIA EL NOMBRE ACTUALIZAR AppBundle\Controller\SecurityController
        firewall_admin:
            pattern: ^/
            anonymous: true            
            logout:
                path: app_logout
                target: app_login
            form_login:
                login_path:           app_login
                remember_me:          false
                check_path:           /login_check

#        public:
#            pattern: "^/recuperar-password/finalizar/(?P<username>[^/]++)/(?P<string_verif>[^/]++)$#sD"
#            security: false

    role_hierarchy:
        # Todos los roles deben extender de ROLE_USUARIO
        ROLE_SEC_ACADEMICA: ROLE_USUARIO
        ROLE_DOCENTE_GRADO: ROLE_USUARIO
        ROLE_ADMIN: ROLE_USUARIO
        
    
    
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recuperar-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recuperar-password/finalizar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuarios, roles: [ROLE_ADMIN] }
        - { path: ^/roles, roles: [ROLE_ADMIN] }
        - { path: ^/permisos, roles: [ROLE_ADMIN] }
        - { path: ^/, roles: [ROLE_USUARIO] }
#        - { path: ^/planificaciones, roles: [ROLE_USUARIO] }












































#security:
#    encoders:
#        AppBundle\Entity\Usuario: plaintext
#        
#        #FOS\UserBundle\Model\UserInterface: bcrypt
#        Symfony\Component\Security\Core\User\User: plaintext
#
#
#    providers:
#        my_memory_provider:
#            memory:
#                users:
#                    emi: { password: '1234', roles: 'ROLE_ADMIN' }
##        fos_userbundle:
##            id: fos_user.user_provider.username
##        default_provider:
##            entity: { class: AppBundle\Entity\Usuario, property: 'username' }
##        in_memory:
##            memory:
##                users:
##                   admin: { password: admin, roles: 'ROLE_ADMIN' }    
#
#    firewalls:
#                # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            pattern: ^/
#            http_basic:
#                provider: my_memory_provider
#                realm: 'Secured Area'
##            form_login:
##                provider: default_provider
##                csrf_token_generator: security.csrf.token_manager
##                default_target_path: /
##                always_use_default_target_path: true
##                # if you are using Symfony < 2.8, use the following config instead:
##                # csrf_provider: form.csrf_provider
##
##            logout:       true
##            anonymous:    true
##            logout:
##                target: /login
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
#        
#    access_control:       
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
##        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
##        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, role: ROLE_ADMIN }
#        
