# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    infofich_viejo_service:
        class: AppBundle\Service\InfofichViejoService
        arguments: ["@doctrine.orm.entity_manager", "%db_infofich_viejo%"]

    api_infofich_service:
        class: AppBundle\Service\APIInfofichService        
        arguments: ["@doctrine.orm.entity_manager"]
        
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
            
    app.apiinfofich.twig_extension:
        class: AppBundle\Twig\APIInfofichExtension
        arguments: ["@api_infofich_service"]
        public: false
        tags:
            - { name: twig.extension }