vehiculos_index:
    path:     /vehiculos
    defaults: { _controller: VehiculosBundle:Default:index }

vehiculos_listado:
    path:     /vehiculos/listado
    defaults: { _controller: "VehiculosBundle:Vehiculo:listado" }
vehiculos_new:
    path:     /vehiculos/new
    defaults: { _controller: "VehiculosBundle:Vehiculo:new" }
    methods:  [GET, POST]
vehiculos_edit:
    path:     /{id}/edit
    defaults: { _controller: "VehiculosBundle:Vehiculo:edit" }
    methods:  [GET, POST]
vehiculos_show:
    path:     /{id}/show
    defaults: { _controller: "VehiculosBundle:Vehiculo:show" }
    methods:  [GET, POST]
vehiculos_delete:
    path:     /{id}/delete
    defaults: { _controller: "VehiculosBundle:Vehiculo:delete" }
    methods:  DELETE


tipo_vehiculos_listado:
    path:     /tipo_vehiculos/listado
    defaults: { _controller: "VehiculosBundle:TipoVehiculo:listado" }
tipo_vehiculos_new:
    path:     /tipo_vehiculos/nuevo
    defaults: { _controller: "VehiculosBundle:TipoVehiculo:new" }
tipo_vehiculos_edit:
    path:     /tipo_vehiculos/{id}/edit
    defaults: { _controller: "VehiculosBundle:TipoVehiculo:edit" }
    methods:  [GET, POST]
tipo_vehiculos_show:
  path:     /tipo_vehiculos/{id}/show
  defaults: { _controller: "VehiculosBundle:TipoVehiculo:show" }
  methods:  [GET]
tipo_vehiculos_delete:
    path:     /tipo_vehiculos/{id}/delete
    defaults: { _controller: "VehiculosBundle:TipoVehiculo:delete" }
    methods:  DELETE
#tipo_delete:
#    path:     /tipo_vehiculos/delete/{id}
#    defaults: { _controller: "VehiculosBundle:TipoVehiculo:deleteTipo" }
#    methods:  [GET, POST]


reservas_listado:
    path:     /reservas/listado
    defaults: { _controller: VehiculosBundle:Reserva:listado }
reservas_new:
    path:     /reservas/new
    defaults: { _controller: "VehiculosBundle:Reserva:new" }
    methods:  [GET, POST]
reservas_edit:
    path:     /reservas/{id}/edit
    defaults: { _controller: "VehiculosBundle:Reserva:edit" }
    methods:  [GET, POST]
reservas_show:
    path:     /reservas/{id}/show
    defaults: { _controller: "VehiculosBundle:Reserva:show" }
    methods:  [GET, POST]
reservas_delete:
    path:     /reservas/{id}/delete
    defaults: { _controller: "VehiculosBundle:Reserva:delete" }
    methods:  DELETE
