vehiculos_index:
    path:     /vehiculos
    defaults: { _controller: VehiculosBundle:Default:index }

vehiculos_listado:
    path:     /vehiculos/listado
    defaults: { _controller: VehiculosBundle:Default:listado }
    
    
    