usuarios_index:
    path:     /
    defaults: { _controller: "AppBundle:Usuario:index" }
    methods:  GET

usuarios_show:
    path:     /{id}/ver
    defaults: { _controller: "AppBundle:Usuario:show" }
    methods:  GET

usuarios_new:
    path:     /nuevo
    defaults: { _controller: "AppBundle:Usuario:new" }
    methods:  [GET, POST]

usuarios_edit:
    path:     /{id}/editar
    defaults: { _controller: "AppBundle:Usuario:edit" }
    methods:  [GET, POST]

usuarios_delete:
    path:     /{id}/borrar
    defaults: { _controller: "AppBundle:Usuario:delete" }
    methods:  DELETE
