#planificaciones_ajax_info_basica:
#    resource: "@PlanificacionesBundle/Resources/config/routing/ajax-info-basica.yml"
#    prefix: /info-basica

planificaciones_ajax_temario:
    resource: "@PlanificacionesBundle/Resources/config/routing/ajax-temario.yml"
    prefix: /temario
    
planificacion_ajax_viajes_academicos:
    resource: "@PlanificacionesBundle/Resources/config/routing/ajax-viajes-academicos.yml"
    prefix: /viajes-academicos
    
planificaciones_ajax_equipo_docente:
    resource: "@PlanificacionesBundle/Resources/config/routing/ajax-equipo-docente.yml"
    prefix: /equipo-docente
    
planificaciones_ajax_cronograma:
    resource: "@PlanificacionesBundle/Resources/config/routing/ajax-cronograma.yml"
    prefix: /cronograma

planificacion_ajax_requisitos_aprob:
    resource: "@PlanificacionesBundle/Resources/config/routing/ajax-aprobacion.yml"
    prefix: /aprobacion

planificaciones_ajax_objetivos:
    resource: "@PlanificacionesBundle/Resources/config/routing/ajax-objetivos.yml"
    prefix: /objetivos

planificacion_ajax_bibliografia:
    resource: "@PlanificacionesBundle/Resources/config/routing/ajax-bibliografia.yml"
    prefix: /bibliografia

planificacion_ajax_distribucion_form:
    resource: "@PlanificacionesBundle/Resources/config/routing/ajax-distribucion.yml"
    prefix: /carga-horaria


