planificaciones_ajax_info_basica:
    resource: "@PlanificacionesBundle/Resources/config/routing/ajax-info-basica.yml"
    prefix: /info-basica

planificaciones_ajax_temario:
    resource: "@PlanificacionesBundle/Resources/config/routing/ajax-temario.yml"
    prefix: /temario
    
planificacion_ajax_get_form_equipo_docente:
    path:     /{id}/equipo-docente
    defaults: { _controller: PlanificacionesBundle:PlanificacionAjax:getFormEquipoDocente }    

planificacion_ajax_get_requisitos_aprob_form:
    path:     /aprobacion
    defaults: { _controller: PlanificacionesBundle:PlanificacionAjax:getRequisitosAprobForm }

planificacion_ajax_get_objetivos_form:
    path:     /objetivos
    defaults: { _controller: PlanificacionesBundle:PlanificacionAjax:getObjetivosForm }

planificacion_ajax_get_bibliografia_form:
    path:     /bibliografia
    defaults: { _controller: PlanificacionesBundle:PlanificacionAjax:getBibliografiaForm }

planificacion_ajax_get_cronograma_form:
    path:     /cronograma
    defaults: { _controller: PlanificacionesBundle:PlanificacionAjax:getCronogramaForm }

planificacion_ajax_get_carga_horaria_form:
    path:     /carga-horaria
    defaults: { _controller: PlanificacionesBundle:PlanificacionAjax:getCargaHorariaForm }

planificacion_ajax_get_viajes_academicos_form:
    path:     /viajes-academicos
    defaults: { _controller: PlanificacionesBundle:PlanificacionAjax:getViajesAcademicosForm }
