#planificacion_equipo_docente_edit:
#    path:     /{id}/editar
#    defaults: { _controller: PlanificacionesBundle:Docentes:edit }    
#    methods: [GET, POST]
#    
## Utilizado cuando se crea
planificaciones_ajax_equipo_docente_get_docente:
    path:     /{pos}/get
    defaults: { _controller: PlanificacionesBundle:Docentes:getDocente }
    methods: [GET]
#    
#planificaciones_ajax_equipo_docente_edit:
#    path:     /{id}/editar
#    defaults: { _controller: PlanificacionesBundle:InfoBasica:edit }
#    methods: [GET, POST]

planif_equipo_docente_editar:
   path: /{id}/equipo-docente/editar
   defaults: { _controller: PlanificacionesBundle:Docentes:edit }
   methods: [GET, POST]