planificaciones_show_notif:
    path:     /mensajes
    defaults: { _controller: PlanificacionesBundle:Planificacion:showNotificacion }
    

planificaciones_homepage:
    path:     /
    defaults: { _controller: PlanificacionesBundle:Planificacion:index }

planificaciones_nueva:
    path:     /nueva
#    defaults: { _controller: PlanificacionesBundle:Planificacion:new }
    defaults: { _controller: PlanificacionesBundle:Planificacion:new }
    methods: [GET, POST]

planificaciones_duplicar:
    path:     /{id}/duplicar
    defaults: { _controller: PlanificacionesBundle:Planificacion:duplicar }
    methods: [GET, POST]
   
planificaciones_borrar:
    path:     /{id}/borrar
    defaults: { _controller: PlanificacionesBundle:Planificacion:borrar }
    methods: [GET, DELETE]
    
planificaciones_revisar:
    path:     /{id}/revisar
    defaults: { _controller: PlanificacionesBundle:Revisar:revisar }
    methods: [GET, POST]
    
planificaciones_enviar_a_correccion:
    path:     /{id}/enviar-a-correccion
    defaults: { _controller: PlanificacionesBundle:Planificacion:enviarACorreccion }
    methods: [GET, POST]
    
planificaciones_publicar:
    path:     /{id}/publicar
    defaults: { _controller: PlanificacionesBundle:Revisar:publicar }
    methods: [GET, POST]
    
planificaciones_get_as_json:
    path:     /{id}/get-as-json
    defaults: { _controller: PlanificacionesBundle:Planificacion:getAsJson }
    methods: [GET]
    
planificaciones_actualizar_comentarios:
    path:     /{id}/actualizar-comentarios
    defaults: { _controller: PlanificacionesBundle:Revisar:actualizarComentarios }
    methods: [GET, POST]

planificaciones_imprimir:
    path:     /{id}/imprimir
    defaults: { _controller: PlanificacionesBundle:Planificacion:imprimir }
    methods: [GET, POST]

planificaciones_cambiar_estado:
    path:     /{id}/cambiar_estado
    defaults: { _controller: PlanificacionesBundle:Planificacion:cambiarEstado }
    methods: [GET, POST]
    
#
#planificaciones_edit:
#    path:     /{id}/editar
#    defaults: { _controller: PlanificacionesBundle:Planificacion:edit }
    