<?php

namespace PlanificacionesBundle\Repository;

/**
 * ActividadCurricularRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadCurricularRepository extends \Doctrine\ORM\EntityRepository
{
}
