<?php

namespace PlanificacionesBundle\Repository;

/**
 * BibliografiaPlanificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibliografiaPlanificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
