<?php

namespace PlanificacionesBundle\Repository;

/**
 * BibliografiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibliografiaRepository extends \Doctrine\ORM\EntityRepository
{
}
