<?php

namespace PlanificacionesBundle\Repository;

/**
 * CargaHorariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargaHorariaRepository extends \Doctrine\ORM\EntityRepository
{
}
