<?php

namespace PlanificacionesBundle\Repository;

/**
 * DocenteAdscriptoPlanificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocenteAdscriptoPlanificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
