<?php

namespace PlanificacionesBundle\Repository;

/**
 * DocenteColaboradorPlanificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocenteColaboradorPlanificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
