<?php

namespace PlanificacionesBundle\Repository;

/**
 * DocenteResponsablePlanificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocenteResponsablePlanificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
