<?php

namespace PlanificacionesBundle\Repository;

/**
 * DocentePlanificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocentePlanificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
