<?php

namespace PlanificacionesBundle\Repository;

/**
 * HistoricoEstadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricoEstadosRepository extends \Doctrine\ORM\EntityRepository
{
}
