<?php

namespace PlanificacionesBundle\Repository;

/**
 * ModuloAsignaturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuloAsignaturaRepository extends \Doctrine\ORM\EntityRepository
{
}
