<?php

namespace PlanificacionesBundle\Repository;

/**
 * PlanificacionDocenteColaboradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanificacionDocenteColaboradorRepository extends \Doctrine\ORM\EntityRepository
{
}
