<?php

namespace PlanificacionesBundle\Repository;

/**
 * PlanificacionDocenteAdscriptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanificacionDocenteAdscriptoRepository extends \Doctrine\ORM\EntityRepository
{
}
