<?php

namespace PlanificacionesBundle\Repository;

/**
 * RequisitosAprobacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequisitosAprobacionRepository extends \Doctrine\ORM\EntityRepository
{
}
