<?php

namespace PlanificacionesBundle\Repository;

/**
 * ResultadosAprendizajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadosAprendizajeRepository extends \Doctrine\ORM\EntityRepository
{
}