<?php

namespace PlanificacionesBundle\Repository;

/**
 * TemarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemarioRepository extends \Doctrine\ORM\EntityRepository
{
}
