<?php

namespace PlanificacionesBundle\Repository;

/**
 * TipoDocenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDocenteRepository extends \Doctrine\ORM\EntityRepository
{
}
