<?php

namespace PlanificacionesBundle\Repository;

/**
 * TipoBibliografiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoBibliografiaRepository extends \Doctrine\ORM\EntityRepository
{
}
