<?php

namespace PlanificacionesBundle\Repository;

/**
 * TipoMovilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoMovilidadRepository extends \Doctrine\ORM\EntityRepository
{
}
