<?php

namespace PlanificacionesBundle\Repository;

/**
 * TipoActividadCurricularRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoActividadCurricularRepository extends \Doctrine\ORM\EntityRepository
{
}
