<?php

namespace PlanificacionesBundle\Repository;

/**
 * VehiculosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculosRepository extends \Doctrine\ORM\EntityRepository
{
}
