<?php

namespace PlanificacionesBundle\Repository;

/**
 * ViajeAcademicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViajeAcademicoRepository extends \Doctrine\ORM\EntityRepository
{
}
