docentes_docentes_adscriptos:
    resource: "@DocentesBundle/Resources/config/routing/docentes-adscriptos.yml"
    prefix:   /docentes/adscriptos

docentes_docentes_grado:
    resource: "@DocentesBundle/Resources/config/routing/docentes-grado.yml"
    prefix:   /docentes/grado

docentes_index:
    path: /docentes
    defaults: { _controller: DocentesBundle:Default:index }

#docentes_adscriptos:
#    path:     /docentes/adscriptos
#    defaults: { _controller: DocentesBundle:Adscriptos:index }
    
#docentes_adscriptos_new:
#    path:     /docentes/adscriptos/nuevo
#    defaults: { _controller: DocentesBundle:Adscriptos:adscriptos }