docentes_index:
    path:     /docentes
    defaults: { _controller: DocentesBundle:Default:index }

docentes_grado:
    path:     /docentes/grado
    defaults: { _controller: DocentesBundle:Default:docentesGrado }

docentes_adscriptos:
    path:     /docentes/adscriptos
    defaults: { _controller: DocentesBundle:Adscriptos:index }
    
docentes_adscriptos_new:
    path:     /docentes/adscriptos/nuevo
    defaults: { _controller: DocentesBundle:Adscriptos:adscriptos }