app_usuarios:
    resource: "@AppBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuarios


homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }
    
#admin_home:
#    path: /home
#    defaults: { _controller: AppBundle:Default:indexAdmin }



app_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

app_logout:
    path:     /logout
    defaults: { _controller: AppBundle:Security:logout }
    
    
ajax_get_asignaturas:
    path:     /asignaturas-por-carrera/{carrera}
    defaults: { _controller: AppBundle:Ajax:getAsignaturas }
    methods: [GET]
    
ajax_get_asignatura:
    path:     /{carrera}/asignaturas/{codigo}
    defaults: { _controller: AppBundle:Ajax:getAsignatura }
    methods: [GET]