services:
    app.form.type.datalist_type:
        class: AppBundle\Form\DatalistType
        tags:
            -  { name: form.type, alias: datalist }
#    app.persona.listener:
#        class: AppBundle\EventListener\PersonaListener
#        tags:
#            - { name: doctrine.event_listener, event: prePersist }